version: '3.8'

services:
  # service name
  server:
    build: ./
    expose:
      - ${APP_SERVER_PORT}
    env_file: ./.env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - CORS_ORIGIN=$CORS_ORIGIN
      - MONGODB_URL=$MONGODB_URL
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:srv/app/ideaflow-backend/src
    command: npm run server

  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/ideaflow-frontend/src
      - ./client/public:/srv/app/ideaflow-frontend/public
    links:
      - server
    command: npm run start