version: "3.8"

services:
  nginx:
    image: akkassingh/ideaflow-app:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    image: akkassingh/ideaflow:client-latest
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
      

  server:
    image: akkassingh/ideaflow:server-latest .
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}