name: CI/CD Pipeline to Docker Hub

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - mainw

# Set environment variables
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  JWT_SECRET:  ${{ secrets.JWT_SECRET }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
  NODE_ENV:    ${{secrets.NODE_ENV}}

# This is the workflow that is being run.
jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the client application
      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          npm run test
      # Install dependencies, export environment variables to be used by application and run tests for the server application
      - name: Install and Test Server
        working-directory: ./
        run: |
          npm install
          export MONGODB_URI=$MONGODB_URI
          export TOKEN_KEY=$TOKEN_KEY
          export EMAIL=$EMAIL
          export PASSWORD=$PASSWORD
