name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build client
        run: |
          cd backend
          npm install
          cd ../client
          npm install
          npm run build

      - name: Set Heroku config vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          NODE_ENV:    ${{secrets.NODE_ENV}}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          JWT_SECRET:  ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          EMAIL_SERVICE:    ${{secrets.EMAIL_SERVICE}}
          EMAIL_USERNAME:   ${{secrets.EMAIL_USERNAME}}
          EMAIL_PASSWORD:   ${{secrets.EMAIL_PASSWORD}}
          EMAIL_FROM:   ${{secrets.EMAIL_FROM}}
          APP_BASE_URL:   ${{secrets.APP_BASE_URL}}
          APP_DISPLAY_NAME:   ${{secrets.APP_DISPLAY_NAME}}
          AWS_BUCKET_NAME:   ${{secrets.AWS_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID:   ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY:   ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          heroku config:set DATABASE_URL=$DATABASE_URL --app your-heroku-app-name
          heroku config:set API_KEY=$API_KEY --app your-heroku-app-name

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/your-heroku-app-name.git
          git add .
          git commit -m "Deploy to Heroku"
          git push heroku main --force
