# The name of the workflow.
name: Build and Deploy

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

# Set environment variables
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

# This is the workflow that is being run.
jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies and run tests for the client application
      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          npm run test

      # Install dependencies, export environment variables to be used by application and run tests for the server application
      - name: Install and Test Server
        working-directory: ./
        run: |
          npm install
          export MONGODB_URI=${{ secrets.MONGODB_URL }}
          export JWT_SECRET=${{ secrets.JWT_SECRET }}
          export SERVER_PORT=${{ secrets.SERVER_PORT }}
          export CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
          export NODE_ENV=${{ secrets.NODE_ENV }}
      
      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"
 
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}