name: Verify Secrets in GitHub Actions


on:
  push:
    branches:
      - main

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Docker Hub username
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is not set"
          exit 1
        else
          echo "DOCKER_USERNAME is set"
        fi

    - name: Verify Docker Hub password
      run: |
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD is not set"
          exit 1
        else
          echo "DOCKER_PASSWORD is set"
        fi

    - name: Verify Heroku API key
      run: |
        if [ -z "${{ secrets.HEROKU_API_KEY }}" ]; then
          echo "HEROKU_API_KEY is not set"
          exit 1
        else
          echo "HEROKU_API_KEY is set"
        fi

    - name: Verify Heroku app name
      run: |
        if [ -z "${{ secrets.HEROKU_APP_NAME }}" ]; then
          echo "HEROKU_APP_NAME is not set"
          exit 1
        else
          echo "HEROKU_APP_NAME is set"
        fi

    - name: Verify Heroku email
      run: |
        if [ -z "${{ secrets.HEROKU_EMAIL }}" ]; then
          echo "HEROKU_EMAIL is not set"
          exit 1
        else
          echo "HEROKU_EMAIL is set"
        fi
